# Generated by Django 5.0 on 2023-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bedrift_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn_bedrift', models.CharField(max_length=255)),
                ('andel_kvinner', models.FloatField()),
                ('andel_data', models.FloatField()),
                ('andel_interreserte', models.FloatField()),
                ('fordeling_klassetrinn', models.FloatField()),
                ('fremforing_presentasjon', models.FloatField()),
                ('innhold_presentasjon', models.FloatField()),
                ('kunnskap_bedrift_pre', models.FloatField()),
                ('kunnskap_bedrift_post', models.FloatField()),
                ('info_jobb', models.FloatField()),
                ('mingling', models.FloatField()),
                ('intterresant_arbeid', models.FloatField()),
                ('sosialt_miljø', models.FloatField()),
                ('arbeidsvilkår', models.FloatField()),
                ('helhetsvurdering', models.FloatField()),
                ('inntrykk_arrangement', models.FloatField()),
            ],
        ),
    ]
