# Generated by Django 5.0 on 2023-12-23 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0002_opplastede_filer'),
    ]

    operations = [
        migrations.AddField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
