# Generated by Django 5.0 on 2023-12-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0007_bedrift_data_dato_bedpres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_bedpres',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 14, 9, 48, 507493)),
        ),
    ]
