# Generated by Django 5.0 on 2023-12-26 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0008_alter_opplastede_filer_dato_bedpres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrift_data',
            name='dato_bedpres',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 14, 10, 39, 202837)),
        ),
    ]
