# Generated by Django 5.0 on 2023-12-26 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0010_bedrift_data_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='semestere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='h23', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 22, 44, 31, 172926)),
        ),
    ]
