# Generated by Django 5.0 on 2024-01-02 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0011_semestere_alter_opplastede_filer_dato_lagret'),
    ]

    operations = [
        migrations.AddField(
            model_name='opplastede_filer',
            name='lunsjpres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 28, 40, 848954)),
        ),
    ]
