# Generated by Django 5.0 on 2024-01-03 20:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_format', '0012_opplastede_filer_lunsjpres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_data',
            name='id_opplastede_filer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csv_format.opplastede_filer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opplastede_filer',
            name='dato_lagret',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 54, 10, 891736)),
        ),
    ]
